//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:58:12 PM CEST 
//


package model.korisnici;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://www.ftn.uns.ac.rs/korisnici}TKorisnik"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="oglasID" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/&amp;gt;
 *         &amp;lt;element name="izvestajID" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded"/&amp;gt;
 *         &amp;lt;element name="komentarID" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="porukaID" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oglasID",
    "izvestajID",
    "komentarID",
    "porukaID"
})
@XmlRootElement(name = "Agent")
public class Agent
    extends TKorisnik
{

    @XmlElement(type = Long.class)
    protected List<Long> oglasID;
    @XmlElement(type = Long.class)
    protected List<Long> izvestajID;
    @XmlElement(type = Long.class)
    protected List<Long> komentarID;
    @XmlElement(type = Long.class)
    protected List<Long> porukaID;

    /**
     * Gets the value of the oglasID property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the oglasID property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getOglasID().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getOglasID() {
        if (oglasID == null) {
            oglasID = new ArrayList<Long>();
        }
        return this.oglasID;
    }

    /**
     * Gets the value of the izvestajID property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the izvestajID property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getIzvestajID().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getIzvestajID() {
        if (izvestajID == null) {
            izvestajID = new ArrayList<Long>();
        }
        return this.izvestajID;
    }

    /**
     * Gets the value of the komentarID property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the komentarID property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getKomentarID().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getKomentarID() {
        if (komentarID == null) {
            komentarID = new ArrayList<Long>();
        }
        return this.komentarID;
    }

    /**
     * Gets the value of the porukaID property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the porukaID property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getPorukaID().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getPorukaID() {
        if (porukaID == null) {
            porukaID = new ArrayList<Long>();
        }
        return this.porukaID;
    }

}
