version: '2'
services:
 db:
  image: postgres
  restart: unless-stopped
  container_name: db
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
 eureka-service:
  image: eureka-app
  build: ./Eureka
  restart: unless-stopped
  container_name: eureka
  ports: 
    - 8761:8761
 zuul:
  environment:
    EUREKA_PATH: http://eureka-service:8761/eureka
  image: zuul-app
  build: ./Zuul
  restart: unless-stopped
  container_name: zuul
  depends_on:
    - eureka-service
  ports: 
    - 2020:2020 
 komentar:
  environment:
    DB_PATH: jdbc:postgresql://db:5432/postgres
    DB_USER: postgres
    DB_PASS: postgres
    EUREKA_PATH: http://eureka-service:8761/eureka
  image: komentar-app
  build: ./Komentar
  restart: unless-stopped
  container_name: komentar
  depends_on:
    - eureka-service
    - db
  links: 
    - eureka-service 
    - db
 