//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.29 at 08:14:42 PM CEST 
//


package model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifikacioniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="brojPredjenihKilometara" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="slodobanTekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voziloID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifikacioniBroj",
    "brojPredjenihKilometara",
    "slodobanTekst",
    "voziloID"
})
@XmlRootElement(name = "Izvestaj", namespace = "http://www.ftn.uns.ac.rs/izvestaj")
public class Izvestaj {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/izvestaj")
    protected long identifikacioniBroj;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/izvestaj", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPredjenihKilometara;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/izvestaj", required = true)
    protected String slodobanTekst;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/izvestaj")
    protected long voziloID;

    /**
     * Gets the value of the identifikacioniBroj property.
     * 
     */
    public long getIdentifikacioniBroj() {
        return identifikacioniBroj;
    }

    /**
     * Sets the value of the identifikacioniBroj property.
     * 
     */
    public void setIdentifikacioniBroj(long value) {
        this.identifikacioniBroj = value;
    }

    /**
     * Gets the value of the brojPredjenihKilometara property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPredjenihKilometara() {
        return brojPredjenihKilometara;
    }

    /**
     * Sets the value of the brojPredjenihKilometara property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPredjenihKilometara(BigInteger value) {
        this.brojPredjenihKilometara = value;
    }

    /**
     * Gets the value of the slodobanTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlodobanTekst() {
        return slodobanTekst;
    }

    /**
     * Sets the value of the slodobanTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlodobanTekst(String value) {
        this.slodobanTekst = value;
    }

    /**
     * Gets the value of the voziloID property.
     * 
     */
    public long getVoziloID() {
        return voziloID;
    }

    /**
     * Sets the value of the voziloID property.
     * 
     */
    public void setVoziloID(long value) {
        this.voziloID = value;
    }

}
