//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.29 at 08:14:42 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifikacioniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="kreatorKomentaraID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="tekstKomentara" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datumVremeKreiranja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="statusKomentara">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="odobren|neodobren"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pomocnoPoljeZaOglas" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifikacioniBroj",
    "kreatorKomentaraID",
    "tekstKomentara",
    "datumVremeKreiranja",
    "statusKomentara",
    "pomocnoPoljeZaOglas"
})
@XmlRootElement(name = "Komentar", namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
public class Komentar {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected long identifikacioniBroj;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected long kreatorKomentaraID;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka", required = true)
    protected String tekstKomentara;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVremeKreiranja;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka", required = true)
    protected String statusKomentara;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected long pomocnoPoljeZaOglas;

    /**
     * Gets the value of the identifikacioniBroj property.
     * 
     */
    public long getIdentifikacioniBroj() {
        return identifikacioniBroj;
    }

    /**
     * Sets the value of the identifikacioniBroj property.
     * 
     */
    public void setIdentifikacioniBroj(long value) {
        this.identifikacioniBroj = value;
    }

    /**
     * Gets the value of the kreatorKomentaraID property.
     * 
     */
    public long getKreatorKomentaraID() {
        return kreatorKomentaraID;
    }

    /**
     * Sets the value of the kreatorKomentaraID property.
     * 
     */
    public void setKreatorKomentaraID(long value) {
        this.kreatorKomentaraID = value;
    }

    /**
     * Gets the value of the tekstKomentara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekstKomentara() {
        return tekstKomentara;
    }

    /**
     * Sets the value of the tekstKomentara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekstKomentara(String value) {
        this.tekstKomentara = value;
    }

    /**
     * Gets the value of the datumVremeKreiranja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVremeKreiranja() {
        return datumVremeKreiranja;
    }

    /**
     * Sets the value of the datumVremeKreiranja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVremeKreiranja(XMLGregorianCalendar value) {
        this.datumVremeKreiranja = value;
    }

    /**
     * Gets the value of the statusKomentara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusKomentara() {
        return statusKomentara;
    }

    /**
     * Sets the value of the statusKomentara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusKomentara(String value) {
        this.statusKomentara = value;
    }

    /**
     * Gets the value of the pomocnoPoljeZaOglas property.
     * 
     */
    public long getPomocnoPoljeZaOglas() {
        return pomocnoPoljeZaOglas;
    }

    /**
     * Sets the value of the pomocnoPoljeZaOglas property.
     * 
     */
    public void setPomocnoPoljeZaOglas(long value) {
        this.pomocnoPoljeZaOglas = value;
    }

}
