//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.29 at 08:14:42 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifikacioniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="vrednostOcene">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;maxInclusive value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="kreatorOceneID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="pomocnoPoljeZaOglas" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifikacioniBroj",
    "vrednostOcene",
    "kreatorOceneID",
    "pomocnoPoljeZaOglas"
})
@XmlRootElement(name = "Ocena", namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
public class Ocena {

    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected long identifikacioniBroj;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected int vrednostOcene;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected long kreatorOceneID;
    @XmlElement(namespace = "http://www.ftn.uns.ac.rs/ocenakomentarporuka")
    protected long pomocnoPoljeZaOglas;

    /**
     * Gets the value of the identifikacioniBroj property.
     * 
     */
    public long getIdentifikacioniBroj() {
        return identifikacioniBroj;
    }

    /**
     * Sets the value of the identifikacioniBroj property.
     * 
     */
    public void setIdentifikacioniBroj(long value) {
        this.identifikacioniBroj = value;
    }

    /**
     * Gets the value of the vrednostOcene property.
     * 
     */
    public int getVrednostOcene() {
        return vrednostOcene;
    }

    /**
     * Sets the value of the vrednostOcene property.
     * 
     */
    public void setVrednostOcene(int value) {
        this.vrednostOcene = value;
    }

    /**
     * Gets the value of the kreatorOceneID property.
     * 
     */
    public long getKreatorOceneID() {
        return kreatorOceneID;
    }

    /**
     * Sets the value of the kreatorOceneID property.
     * 
     */
    public void setKreatorOceneID(long value) {
        this.kreatorOceneID = value;
    }

    /**
     * Gets the value of the pomocnoPoljeZaOglas property.
     * 
     */
    public long getPomocnoPoljeZaOglas() {
        return pomocnoPoljeZaOglas;
    }

    /**
     * Sets the value of the pomocnoPoljeZaOglas property.
     * 
     */
    public void setPomocnoPoljeZaOglas(long value) {
        this.pomocnoPoljeZaOglas = value;
    }

}
