//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:56:49 PM CEST 
//


package model.cenovnik;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifikacioniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *         &amp;lt;element name="cenaZaDan" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
 *         &amp;lt;element name="cenaViseOd30" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="cenaPoKilometruZaOgranicenuKilometrazu" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="cenaCDW" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifikacioniBroj",
    "cenaZaDan",
    "cenaViseOd30",
    "cenaPoKilometruZaOgranicenuKilometrazu",
    "cenaCDW"
})
@XmlRootElement(name = "Cenovnik")
public class Cenovnik {

    protected long identifikacioniBroj;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cenaZaDan;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cenaViseOd30;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cenaPoKilometruZaOgranicenuKilometrazu;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger cenaCDW;

    /**
     * Gets the value of the identifikacioniBroj property.
     * 
     */
    public long getIdentifikacioniBroj() {
        return identifikacioniBroj;
    }

    /**
     * Sets the value of the identifikacioniBroj property.
     * 
     */
    public void setIdentifikacioniBroj(long value) {
        this.identifikacioniBroj = value;
    }

    /**
     * Gets the value of the cenaZaDan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCenaZaDan() {
        return cenaZaDan;
    }

    /**
     * Sets the value of the cenaZaDan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCenaZaDan(BigInteger value) {
        this.cenaZaDan = value;
    }

    /**
     * Gets the value of the cenaViseOd30 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCenaViseOd30() {
        return cenaViseOd30;
    }

    /**
     * Sets the value of the cenaViseOd30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCenaViseOd30(BigInteger value) {
        this.cenaViseOd30 = value;
    }

    /**
     * Gets the value of the cenaPoKilometruZaOgranicenuKilometrazu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCenaPoKilometruZaOgranicenuKilometrazu() {
        return cenaPoKilometruZaOgranicenuKilometrazu;
    }

    /**
     * Sets the value of the cenaPoKilometruZaOgranicenuKilometrazu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCenaPoKilometruZaOgranicenuKilometrazu(BigInteger value) {
        this.cenaPoKilometruZaOgranicenuKilometrazu = value;
    }

    /**
     * Gets the value of the cenaCDW property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCenaCDW() {
        return cenaCDW;
    }

    /**
     * Sets the value of the cenaCDW property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCenaCDW(BigInteger value) {
        this.cenaCDW = value;
    }

}
