//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:59:12 PM CEST 
//


package model.obican_korisnik_pretraga;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.obican_korisnik_pretraga package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Vozilo_QNAME = new QName("http://www.ftn.uns.ac.rs/vozilo", "Vozilo");
    private final static QName _Administrator_QNAME = new QName("http://www.ftn.uns.ac.rs/korisnici", "Administrator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.obican_korisnik_pretraga
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pretraga }
     * 
     */
    public Pretraga createPretraga() {
        return new Pretraga();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link Pretraga.NaprednaPretraga }
     * 
     */
    public Pretraga.NaprednaPretraga createPretragaNaprednaPretraga() {
        return new Pretraga.NaprednaPretraga();
    }

    /**
     * Create an instance of {@link TVozilo }
     * 
     */
    public TVozilo createTVozilo() {
        return new TVozilo();
    }

    /**
     * Create an instance of {@link TKlasaVozila }
     * 
     */
    public TKlasaVozila createTKlasaVozila() {
        return new TKlasaVozila();
    }

    /**
     * Create an instance of {@link TMarkaVozila }
     * 
     */
    public TMarkaVozila createTMarkaVozila() {
        return new TMarkaVozila();
    }

    /**
     * Create an instance of {@link TModelVozila }
     * 
     */
    public TModelVozila createTModelVozila() {
        return new TModelVozila();
    }

    /**
     * Create an instance of {@link TVrstaGoriva }
     * 
     */
    public TVrstaGoriva createTVrstaGoriva() {
        return new TVrstaGoriva();
    }

    /**
     * Create an instance of {@link TTipMenjaca }
     * 
     */
    public TTipMenjaca createTTipMenjaca() {
        return new TTipMenjaca();
    }

    /**
     * Create an instance of {@link TSlika }
     * 
     */
    public TSlika createTSlika() {
        return new TSlika();
    }

    /**
     * Create an instance of {@link RegistrovaniKorisnik }
     * 
     */
    public RegistrovaniKorisnik createRegistrovaniKorisnik() {
        return new RegistrovaniKorisnik();
    }

    /**
     * Create an instance of {@link TKorisnik }
     * 
     */
    public TKorisnik createTKorisnik() {
        return new TKorisnik();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Firma }
     * 
     */
    public Firma createFirma() {
        return new Firma();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TVozilo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TVozilo }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/vozilo", name = "Vozilo")
    public JAXBElement<TVozilo> createVozilo(TVozilo value) {
        return new JAXBElement<TVozilo>(_Vozilo_QNAME, TVozilo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TKorisnik }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TKorisnik }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/korisnici", name = "Administrator")
    public JAXBElement<TKorisnik> createAdministrator(TKorisnik value) {
        return new JAXBElement<TKorisnik>(_Administrator_QNAME, TKorisnik.class, null, value);
    }

}
