//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:59:12 PM CEST 
//


package model.obican_korisnik_pretraga;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="mestoPreuzimanja" type="{http://www.ftn.uns.ac.rs/korisnici}TAdresa"/&amp;gt;
 *         &amp;lt;element name="datumPreuzimanja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="datumPovratka" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="naprednaPretraga"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;extension base="{http://www.ftn.uns.ac.rs/vozilo}TVozilo"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="cenaOd" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
 *                   &amp;lt;element name="cenaDo" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/extension&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mestoPreuzimanja",
    "datumPreuzimanja",
    "datumPovratka",
    "naprednaPretraga"
})
@XmlRootElement(name = "Pretraga", namespace = " http://www.ftn.uns.ac.rs/pretraga")
public class Pretraga {

    @XmlElement(namespace = " http://www.ftn.uns.ac.rs/pretraga", required = true)
    protected TAdresa mestoPreuzimanja;
    @XmlElement(namespace = " http://www.ftn.uns.ac.rs/pretraga", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPreuzimanja;
    @XmlElement(namespace = " http://www.ftn.uns.ac.rs/pretraga", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPovratka;
    @XmlElement(namespace = " http://www.ftn.uns.ac.rs/pretraga", required = true)
    protected Pretraga.NaprednaPretraga naprednaPretraga;

    /**
     * Gets the value of the mestoPreuzimanja property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getMestoPreuzimanja() {
        return mestoPreuzimanja;
    }

    /**
     * Sets the value of the mestoPreuzimanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setMestoPreuzimanja(TAdresa value) {
        this.mestoPreuzimanja = value;
    }

    /**
     * Gets the value of the datumPreuzimanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPreuzimanja() {
        return datumPreuzimanja;
    }

    /**
     * Sets the value of the datumPreuzimanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPreuzimanja(XMLGregorianCalendar value) {
        this.datumPreuzimanja = value;
    }

    /**
     * Gets the value of the datumPovratka property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPovratka() {
        return datumPovratka;
    }

    /**
     * Sets the value of the datumPovratka property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPovratka(XMLGregorianCalendar value) {
        this.datumPovratka = value;
    }

    /**
     * Gets the value of the naprednaPretraga property.
     * 
     * @return
     *     possible object is
     *     {@link Pretraga.NaprednaPretraga }
     *     
     */
    public Pretraga.NaprednaPretraga getNaprednaPretraga() {
        return naprednaPretraga;
    }

    /**
     * Sets the value of the naprednaPretraga property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pretraga.NaprednaPretraga }
     *     
     */
    public void setNaprednaPretraga(Pretraga.NaprednaPretraga value) {
        this.naprednaPretraga = value;
    }


    /**
     * &lt;p&gt;Java class for anonymous complex type.
     * 
     * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
     * 
     * &lt;pre&gt;
     * &amp;lt;complexType&amp;gt;
     *   &amp;lt;complexContent&amp;gt;
     *     &amp;lt;extension base="{http://www.ftn.uns.ac.rs/vozilo}TVozilo"&amp;gt;
     *       &amp;lt;sequence&amp;gt;
     *         &amp;lt;element name="cenaOd" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
     *         &amp;lt;element name="cenaDo" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
     *       &amp;lt;/sequence&amp;gt;
     *     &amp;lt;/extension&amp;gt;
     *   &amp;lt;/complexContent&amp;gt;
     * &amp;lt;/complexType&amp;gt;
     * &lt;/pre&gt;
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cenaOd",
        "cenaDo"
    })
    public static class NaprednaPretraga
        extends TVozilo
    {

        @XmlElement(namespace = " http://www.ftn.uns.ac.rs/pretraga", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger cenaOd;
        @XmlElement(namespace = " http://www.ftn.uns.ac.rs/pretraga", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger cenaDo;

        /**
         * Gets the value of the cenaOd property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCenaOd() {
            return cenaOd;
        }

        /**
         * Sets the value of the cenaOd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCenaOd(BigInteger value) {
            this.cenaOd = value;
        }

        /**
         * Gets the value of the cenaDo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCenaDo() {
            return cenaDo;
        }

        /**
         * Sets the value of the cenaDo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCenaDo(BigInteger value) {
            this.cenaDo = value;
        }

    }

}
