//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:59:12 PM CEST 
//


package model.obican_korisnik_pretraga;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for TVozilo complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="TVozilo"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifikacioniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *         &amp;lt;element name="klasaVozila" type="{http://www.ftn.uns.ac.rs/vozilo}TKlasaVozila"/&amp;gt;
 *         &amp;lt;element name="markaVozila" type="{http://www.ftn.uns.ac.rs/vozilo}TMarkaVozila"/&amp;gt;
 *         &amp;lt;element name="modelVozila" type="{http://www.ftn.uns.ac.rs/vozilo}TModelVozila"/&amp;gt;
 *         &amp;lt;element name="vrstaGoriva" type="{http://www.ftn.uns.ac.rs/vozilo}TVrstaGoriva"/&amp;gt;
 *         &amp;lt;element name="tipMenjaca" type="{http://www.ftn.uns.ac.rs/vozilo}TTipMenjaca"/&amp;gt;
 *         &amp;lt;element name="slika" type="{http://www.ftn.uns.ac.rs/vozilo}TSlika" maxOccurs="unbounded"/&amp;gt;
 *         &amp;lt;element name="predjenaKilometraza" type="{http://www.w3.org/2001/XMLSchema}float"/&amp;gt;
 *         &amp;lt;element name="brojSedistaZaDecu" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&amp;gt;
 *         &amp;lt;element name="planiranaKilometraza" type="{http://www.w3.org/2001/XMLSchema}float"/&amp;gt;
 *         &amp;lt;element name="collisiondamageWaiver" type="{http://www.w3.org/2001/XMLSchema}boolean"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVozilo", propOrder = {
    "identifikacioniBroj",
    "klasaVozila",
    "markaVozila",
    "modelVozila",
    "vrstaGoriva",
    "tipMenjaca",
    "slika",
    "predjenaKilometraza",
    "brojSedistaZaDecu",
    "planiranaKilometraza",
    "collisiondamageWaiver"
})
@XmlSeeAlso({
    model.obican_korisnik_pretraga.Pretraga.NaprednaPretraga.class
})
public class TVozilo {

    protected long identifikacioniBroj;
    @XmlElement(required = true)
    protected TKlasaVozila klasaVozila;
    @XmlElement(required = true)
    protected TMarkaVozila markaVozila;
    @XmlElement(required = true)
    protected TModelVozila modelVozila;
    @XmlElement(required = true)
    protected TVrstaGoriva vrstaGoriva;
    @XmlElement(required = true)
    protected TTipMenjaca tipMenjaca;
    @XmlElement(required = true)
    protected List<TSlika> slika;
    protected float predjenaKilometraza;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojSedistaZaDecu;
    protected float planiranaKilometraza;
    protected boolean collisiondamageWaiver;

    /**
     * Gets the value of the identifikacioniBroj property.
     * 
     */
    public long getIdentifikacioniBroj() {
        return identifikacioniBroj;
    }

    /**
     * Sets the value of the identifikacioniBroj property.
     * 
     */
    public void setIdentifikacioniBroj(long value) {
        this.identifikacioniBroj = value;
    }

    /**
     * Gets the value of the klasaVozila property.
     * 
     * @return
     *     possible object is
     *     {@link TKlasaVozila }
     *     
     */
    public TKlasaVozila getKlasaVozila() {
        return klasaVozila;
    }

    /**
     * Sets the value of the klasaVozila property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKlasaVozila }
     *     
     */
    public void setKlasaVozila(TKlasaVozila value) {
        this.klasaVozila = value;
    }

    /**
     * Gets the value of the markaVozila property.
     * 
     * @return
     *     possible object is
     *     {@link TMarkaVozila }
     *     
     */
    public TMarkaVozila getMarkaVozila() {
        return markaVozila;
    }

    /**
     * Sets the value of the markaVozila property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMarkaVozila }
     *     
     */
    public void setMarkaVozila(TMarkaVozila value) {
        this.markaVozila = value;
    }

    /**
     * Gets the value of the modelVozila property.
     * 
     * @return
     *     possible object is
     *     {@link TModelVozila }
     *     
     */
    public TModelVozila getModelVozila() {
        return modelVozila;
    }

    /**
     * Sets the value of the modelVozila property.
     * 
     * @param value
     *     allowed object is
     *     {@link TModelVozila }
     *     
     */
    public void setModelVozila(TModelVozila value) {
        this.modelVozila = value;
    }

    /**
     * Gets the value of the vrstaGoriva property.
     * 
     * @return
     *     possible object is
     *     {@link TVrstaGoriva }
     *     
     */
    public TVrstaGoriva getVrstaGoriva() {
        return vrstaGoriva;
    }

    /**
     * Sets the value of the vrstaGoriva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVrstaGoriva }
     *     
     */
    public void setVrstaGoriva(TVrstaGoriva value) {
        this.vrstaGoriva = value;
    }

    /**
     * Gets the value of the tipMenjaca property.
     * 
     * @return
     *     possible object is
     *     {@link TTipMenjaca }
     *     
     */
    public TTipMenjaca getTipMenjaca() {
        return tipMenjaca;
    }

    /**
     * Sets the value of the tipMenjaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipMenjaca }
     *     
     */
    public void setTipMenjaca(TTipMenjaca value) {
        this.tipMenjaca = value;
    }

    /**
     * Gets the value of the slika property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the slika property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getSlika().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link TSlika }
     * 
     * 
     */
    public List<TSlika> getSlika() {
        if (slika == null) {
            slika = new ArrayList<TSlika>();
        }
        return this.slika;
    }

    /**
     * Gets the value of the predjenaKilometraza property.
     * 
     */
    public float getPredjenaKilometraza() {
        return predjenaKilometraza;
    }

    /**
     * Sets the value of the predjenaKilometraza property.
     * 
     */
    public void setPredjenaKilometraza(float value) {
        this.predjenaKilometraza = value;
    }

    /**
     * Gets the value of the brojSedistaZaDecu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojSedistaZaDecu() {
        return brojSedistaZaDecu;
    }

    /**
     * Sets the value of the brojSedistaZaDecu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojSedistaZaDecu(BigInteger value) {
        this.brojSedistaZaDecu = value;
    }

    /**
     * Gets the value of the planiranaKilometraza property.
     * 
     */
    public float getPlaniranaKilometraza() {
        return planiranaKilometraza;
    }

    /**
     * Sets the value of the planiranaKilometraza property.
     * 
     */
    public void setPlaniranaKilometraza(float value) {
        this.planiranaKilometraza = value;
    }

    /**
     * Gets the value of the collisiondamageWaiver property.
     * 
     */
    public boolean isCollisiondamageWaiver() {
        return collisiondamageWaiver;
    }

    /**
     * Sets the value of the collisiondamageWaiver property.
     * 
     */
    public void setCollisiondamageWaiver(boolean value) {
        this.collisiondamageWaiver = value;
    }

}
