//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:53:23 PM CEST 
//


package model.ocena_komentar_poruka;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="identifikacioniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *         &amp;lt;element name="kreatorPorukeID" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *         &amp;lt;element name="primalacPorukeID" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *         &amp;lt;element name="tekstPoruke" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *         &amp;lt;element name="datumVremeKreiranja" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&amp;gt;
 *         &amp;lt;element name="zahtevZaIznajmljivanjeID" type="{http://www.w3.org/2001/XMLSchema}long"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifikacioniBroj",
    "kreatorPorukeID",
    "primalacPorukeID",
    "tekstPoruke",
    "datumVremeKreiranja",
    "zahtevZaIznajmljivanjeID"
})
@XmlRootElement(name = "Poruka")
public class Poruka {

    protected long identifikacioniBroj;
    protected long kreatorPorukeID;
    protected long primalacPorukeID;
    @XmlElement(required = true)
    protected String tekstPoruke;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVremeKreiranja;
    protected long zahtevZaIznajmljivanjeID;

    /**
     * Gets the value of the identifikacioniBroj property.
     * 
     */
    public long getIdentifikacioniBroj() {
        return identifikacioniBroj;
    }

    /**
     * Sets the value of the identifikacioniBroj property.
     * 
     */
    public void setIdentifikacioniBroj(long value) {
        this.identifikacioniBroj = value;
    }

    /**
     * Gets the value of the kreatorPorukeID property.
     * 
     */
    public long getKreatorPorukeID() {
        return kreatorPorukeID;
    }

    /**
     * Sets the value of the kreatorPorukeID property.
     * 
     */
    public void setKreatorPorukeID(long value) {
        this.kreatorPorukeID = value;
    }

    /**
     * Gets the value of the primalacPorukeID property.
     * 
     */
    public long getPrimalacPorukeID() {
        return primalacPorukeID;
    }

    /**
     * Sets the value of the primalacPorukeID property.
     * 
     */
    public void setPrimalacPorukeID(long value) {
        this.primalacPorukeID = value;
    }

    /**
     * Gets the value of the tekstPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekstPoruke() {
        return tekstPoruke;
    }

    /**
     * Sets the value of the tekstPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekstPoruke(String value) {
        this.tekstPoruke = value;
    }

    /**
     * Gets the value of the datumVremeKreiranja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVremeKreiranja() {
        return datumVremeKreiranja;
    }

    /**
     * Sets the value of the datumVremeKreiranja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVremeKreiranja(XMLGregorianCalendar value) {
        this.datumVremeKreiranja = value;
    }

    /**
     * Gets the value of the zahtevZaIznajmljivanjeID property.
     * 
     */
    public long getZahtevZaIznajmljivanjeID() {
        return zahtevZaIznajmljivanjeID;
    }

    /**
     * Sets the value of the zahtevZaIznajmljivanjeID property.
     * 
     */
    public void setZahtevZaIznajmljivanjeID(long value) {
        this.zahtevZaIznajmljivanjeID = value;
    }

}
