//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 07:58:12 PM CEST 
//


package com.adminservis.AdminServis.model;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.korisnici package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Administrator_QNAME = new QName("http://www.ftn.uns.ac.rs/korisnici", "Administrator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.korisnici
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistrovaniKorisnik }
     * 
     */
    public RegistrovaniKorisnik createRegistrovaniKorisnik() {
        return new RegistrovaniKorisnik();
    }

    /**
     * Create an instance of {@link TKorisnik }
     * 
     */
    public TKorisnik createTKorisnik() {
        return new TKorisnik();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Firma }
     * 
     */
    public Firma createFirma() {
        return new Firma();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TKorisnik }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TKorisnik }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/korisnici", name = "Administrator")
    public JAXBElement<TKorisnik> createAdministrator(TKorisnik value) {
        return new JAXBElement<TKorisnik>(_Administrator_QNAME, TKorisnik.class, null, value);
    }

}
