//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.28 at 08:05:38 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/vozilo", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model.vozilo;
